# Generated by Django 5.2.8 on 2026-01-06 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's full name", max_length=200)),
                ('email', models.EmailField(help_text="Sender's email address", max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(help_text='Subject of the message', max_length=300)),
                ('message', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False, help_text='Has this been read by admin?')),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contacts_co_created_e8049d_idx'), models.Index(fields=['is_read'], name='contacts_co_is_read_e891bd_idx')],
            },
        ),
    ]
