# Generated by Django 5.2.8 on 2026-04-15 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('placement', models.CharField(choices=[('hero', 'Hero'), ('announcement', 'Announcement')], default='hero', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media-assets/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('utility', 'Utility')], default='header', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['menu', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('template', models.CharField(blank=True, default='default', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='page-sections/')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=255, unique=True)),
                ('target_url', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent Redirect'), (302, '302 Temporary Redirect')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_path'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('site_name', models.CharField(default='Jambo Rafiki', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('primary_color', models.CharField(blank=True, max_length=32)),
                ('secondary_color', models.CharField(blank=True, max_length=32)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('seo_default_title', models.CharField(blank=True, max_length=255)),
                ('seo_default_description', models.TextField(blank=True)),
                ('homepage_title', models.CharField(blank=True, max_length=255)),
                ('homepage_subtitle', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='core_audite_event_t_2e3170_idx',
            old_name='core_audite_event_t_1b1c71_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='core_audite_target__cc0e25_idx',
            old_name='core_audite_target__22fc8d_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='core_backgr_status_93f877_idx',
            old_name='core_backgr_status_758e32_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='core_backgr_job_typ_0774c3_idx',
            old_name='core_backgr_job_typ_7b96f7_idx',
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['placement', 'is_active', '-priority'], name='core_banner_placeme_8614b5_idx'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['category', '-created_at'], name='core_mediaa_categor_933635_idx'),
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.navigationmenu'),
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationmenuitem'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.page'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.page'),
        ),
        migrations.AddIndex(
            model_name='redirectrule',
            index=models.Index(fields=['is_active', 'source_path'], name='core_redire_is_acti_ee34d5_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrevision',
            index=models.Index(fields=['entity_type', 'entity_id', '-version'], name='core_conten_entity__02fc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrevision',
            index=models.Index(fields=['status', '-created_at'], name='core_conten_status_0c9cf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_id', 'version'), name='uniq_content_revision_entity_version'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', '-updated_at'], name='core_page_status_beafc6_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='core_page_slug_904ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationmenuitem',
            index=models.Index(fields=['menu', 'is_active', 'sort_order'], name='core_naviga_menu_id_03e929_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['page', 'is_active', 'sort_order'], name='core_pagese_page_id_4a8976_idx'),
        ),
    ]
