# Generated by Django 5.2.8 on 2026-01-06 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('email', models.EmailField(help_text='Email address', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('location', models.CharField(help_text='City/Country', max_length=200)),
                ('skills', models.TextField(help_text='Skills and expertise')),
                ('availability', models.CharField(help_text='When are you available?', max_length=500)),
                ('duration', models.CharField(help_text='How long can you volunteer?', max_length=200)),
                ('motivation', models.TextField(help_text='Why do you want to volunteer with us?')),
                ('experience', models.TextField(blank=True, help_text='Previous volunteer experience')),
                ('areas_of_interest', models.TextField(blank=True, help_text='Which programs interest you? (Education, Health, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
            ],
            options={
                'verbose_name': 'Volunteer Application',
                'verbose_name_plural': 'Volunteer Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='volunteers__created_3f59f6_idx'), models.Index(fields=['status'], name='volunteers__status_664c3f_idx')],
            },
        ),
    ]
