# Generated by Django 5.2.8 on 2026-01-06 12:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(help_text="Donor's full name", max_length=200)),
                ('donor_email', models.EmailField(help_text="Donor's email", max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('donor_phone', models.CharField(blank=True, help_text="Donor's phone number", max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Keep donation anonymous')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', max_length=3)),
                ('donation_type', models.CharField(choices=[('one_time', 'One-time Donation'), ('monthly', 'Monthly Sponsorship'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='one_time', max_length=20)),
                ('purpose', models.CharField(blank=True, help_text='Purpose of donation', max_length=300)),
                ('message', models.TextField(blank=True, help_text='Message from donor')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('stripe', 'Credit/Debit Card (Stripe)'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(help_text='Payment transaction ID', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=100)),
                ('mpesa_phone', models.CharField(blank=True, max_length=15)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=200)),
                ('paypal_order_id', models.CharField(blank=True, max_length=200)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='donations_d_created_7012d0_idx'), models.Index(fields=['status'], name='donations_d_status_73ca83_idx'), models.Index(fields=['payment_method'], name='donations_d_payment_ef61a1_idx'), models.Index(fields=['donor_email'], name='donations_d_donor_e_914ea9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DonationCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='donations.donation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
