# Generated by Django 5.2.8 on 2026-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='receipt_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
