# Generated by Django 5.2.8 on 2026-04-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
