# Generated by Django 5.2.8 on 2026-04-15

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_mpesa_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcallback',
            name='external_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donationcallback',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='donationcallback',
            name='processing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='donationcallback',
            index=models.Index(fields=['provider', 'external_id'], name='donations_d_provider_1b30ec_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcallback',
            index=models.Index(fields=['provider', 'payload_hash'], name='donations_d_provider_35f896_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcallback',
            index=models.Index(fields=['processed', '-created_at'], name='donations_d_process_4bc388_idx'),
        ),
        migrations.AddConstraint(
            model_name='donationcallback',
            constraint=models.UniqueConstraint(condition=~Q(external_id=''), fields=('provider', 'external_id'), name='uniq_donationcallback_provider_external_id'),
        ),
        migrations.AddConstraint(
            model_name='donationcallback',
            constraint=models.UniqueConstraint(condition=~Q(payload_hash=''), fields=('provider', 'payload_hash'), name='uniq_donationcallback_provider_payload_hash'),
        ),
    ]
