# Generated by Django 5.2.8 on 2026-04-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donationcallback_replay_and_observability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcallback',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='donationcallback',
            name='requires_reconciliation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationcallback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_method', 'status', '-created_at'], name='donations_d_payment_ccff8c_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'updated_at'], name='donations_d_status_b41e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcallback',
            index=models.Index(fields=['requires_reconciliation', '-created_at'], name='donations_d_requires_e00f4e_idx'),
        ),
    ]
