# Generated by Django 5.2.8 on 2026-04-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_callback_reconciliation_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='donation',
            new_name='donations_d_payment_5fa022_idx',
            old_name='donations_d_payment_ccff8c_idx',
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='donations_d_status_96d705_idx',
            old_name='donations_d_status_b41e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='donationcallback',
            new_name='donations_d_provide_1473d4_idx',
            old_name='donations_d_provider_1b30ec_idx',
        ),
        migrations.RenameIndex(
            model_name='donationcallback',
            new_name='donations_d_provide_48effe_idx',
            old_name='donations_d_provider_35f896_idx',
        ),
        migrations.RenameIndex(
            model_name='donationcallback',
            new_name='donations_d_process_0687da_idx',
            old_name='donations_d_process_4bc388_idx',
        ),
        migrations.RenameIndex(
            model_name='donationcallback',
            new_name='donations_d_require_4f9451_idx',
            old_name='donations_d_requires_e00f4e_idx',
        ),
    ]
