# Generated by Django 5.2.8 on 2026-01-06 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('preferred_level', models.CharField(blank=True, choices=[('Basic', 'Basic Sponsorship'), ('Premium', 'Premium Sponsorship'), ('Full', 'Full Sponsorship')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProgressReport',
        ),
        migrations.DeleteModel(
            name='SponsorshipPayment',
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='child',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
