# Generated by Django 5.2.8 on 2026-03-21 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person giving the testimonial', max_length=200)),
                ('email', models.EmailField(help_text='Email address (not displayed publicly)', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('community_member', 'Community Member'), ('volunteer', 'Volunteer'), ('donor', 'Donor'), ('sponsor', 'Sponsor'), ('partner', 'Partner Organisation'), ('other', 'Other')], default='other', help_text='Relationship to Jambo Rafiki', max_length=30)),
                ('role_custom', models.CharField(blank=True, help_text='Custom role title to display (overrides role choice if set)', max_length=100)),
                ('text', models.TextField(help_text='The testimonial message')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes (not shown publicly)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-approved_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='testimonial_status_c6beca_idx'), models.Index(fields=['-created_at'], name='testimonial_created_f57fe8_idx')],
            },
        ),
    ]
